package challenges.week_2.fibonacci;

public class FibonacciSequence {
    // Prints each index of Array generated by fibonacciArray
    public static void printFibonacci(int limit) {
        if (limit == 0) {
            System.out.println();
        } else {
            for (int i : fibonacciArray(limit))
                System.out.println(i);
        }
    }

    // Contains the recursive logic for calculating the fibonacci sequence up to a given number
    private static int fibonacciUpTo(int n) {
        if (n == 0) {
            return 0;
        } else if (n == 1 || n == 2) {
            return 1;
        }
        return fibonacciUpTo(n - 2) + fibonacciUpTo(n - 1);
    }

    // Stores the output of fibonacciUpTo in an int array for testing and printing
    public static int[] fibonacciArray(int limit) {
        int[] sequence;
        if (limit == 0) {
            return null;
        } else {
            sequence = new int[limit];
            for (int i = 0; i < limit; i++) {
                sequence[i] = fibonacciUpTo(i);
            }
        }
        return sequence;
    }
}
